version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./media:/app/media
      - ./logs:/var/log
    environment:
      - DEBUG=True
      - USE_POSTGRES=False
      - USE_S3=False
      - SECRET_KEY=dev-secret-key-change-in-production
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=gaspack_rwa_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: 